import 'package:flutter/material.dart';
import '../../../../gen_models/models_library.dart';

// ── ProjectReport Form Widget  |  Fields: projectId, reportType, title, content, data, generatedBy

class ProjectReportFormWidget extends StatefulWidget {
  final ProjectReport? item;
  final void Function(ProjectReport)? onSubmit;
  const ProjectReportFormWidget({super.key, this.item, this.onSubmit});
  @override State<ProjectReportFormWidget> createState() => _ProjectReportFormWidgetState();
}

class _ProjectReportFormWidgetState extends State<ProjectReportFormWidget> {
  final _key = GlobalKey<FormState>();
  String? _projectId;
  String? _reportType;
  String? _title;
  String? _content;
  String? _data;
  String? _generatedBy;

  @override
  void initState() {
    super.initState();
    _projectId = widget.item?.projectId?.toString();
    _reportType = widget.item?.reportType?.toString();
    _title = widget.item?.title?.toString();
    _content = widget.item?.content?.toString();
    _data = widget.item?.data?.toString();
    _generatedBy = widget.item?.generatedBy?.toString();
  }

  @override
  void dispose() {
    super.dispose();
  }

  void _submit() {
    if (!_key.currentState!.validate()) return;
    _key.currentState!.save();
    final data = <String, dynamic>{
        if (_projectId?.isNotEmpty == true) 'projectId': _projectId,
        if (_reportType?.isNotEmpty == true) 'reportType': _reportType,
        if (_title?.isNotEmpty == true) 'title': _title,
        if (_content?.isNotEmpty == true) 'content': _content,
        if (_data?.isNotEmpty == true) 'data': _data,
        if (_generatedBy?.isNotEmpty == true) 'generatedBy': _generatedBy,
    };
    final result = widget.item != null
        ? ProjectReport.fromJson({...widget.item!.toJson(), ...data})
        : ProjectReport.fromJson(data);
    widget.onSubmit?.call(result);
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _key,
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(4),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
              TextFormField(
                decoration: InputDecoration(labelText: 'Project Id', prefixIcon: const Icon(Icons.link), border: const OutlineInputBorder()),
                onSaved: (v) => _projectId = v?.isEmpty == true ? null : v,
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: InputDecoration(labelText: 'Report Type', prefixIcon: const Icon(Icons.text_fields), border: const OutlineInputBorder()),
                onSaved: (v) => _reportType = v?.isEmpty == true ? null : v,
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: InputDecoration(labelText: 'Title', prefixIcon: const Icon(Icons.text_fields), border: const OutlineInputBorder()),
                onSaved: (v) => _title = v?.isEmpty == true ? null : v,
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: InputDecoration(labelText: 'Content', prefixIcon: const Icon(Icons.notes), border: const OutlineInputBorder()),
                onSaved: (v) => _content = v?.isEmpty == true ? null : v,
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: InputDecoration(labelText: 'Data', prefixIcon: const Icon(Icons.text_fields), border: const OutlineInputBorder()),
                onSaved: (v) => _data = v?.isEmpty == true ? null : v,
              ),
              const SizedBox(height: 12),
              TextFormField(
                decoration: InputDecoration(labelText: 'Generated By', prefixIcon: const Icon(Icons.attach_money), border: const OutlineInputBorder()),
                onSaved: (v) => _generatedBy = v?.isEmpty == true ? null : v,
              ),
              const SizedBox(height: 12),
            FilledButton.icon(
              onPressed: _submit,
              icon: Icon(widget.item != null ? Icons.save : Icons.add),
              label: Text(widget.item != null ? 'Save Changes' : 'Create Project Report'),
              style: FilledButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 14)),
            ),
          ],
        ),
      ),
    );
  }
}

String _fmt(DateTime? d) {
  if (d == null) return 'N/A';
  final mo = d.month.toString().padLeft(2,'0');
  final day = d.day.toString().padLeft(2,'0');
  final h = d.hour.toString().padLeft(2,'0');
  final mi = d.minute.toString().padLeft(2,'0');
  return '${d.year}-$mo-$day $h:$mi';
}