from typing import List, Dict, Any, Optional
from pydantic import BaseModel
import io

class BrochureInput(BaseModel):
    property_id: Optional[str] = None
    template: str = "modern_1"
    custom_photos: Optional[List[str]] = None
    title: Optional[str] = None
    address: Optional[str] = None
    description: Optional[str] = None
    price: Optional[float] = None
    bedrooms: Optional[int] = None
    bathrooms: Optional[int] = None
    sqft: Optional[int] = None

def get_templates() -> list:
    return [
        {
            "id": "modern_1",
            "name": "Modern Elegance",
            "description": "A clean, modern style brochure focusing on large high-quality photos.",
            "isPremium": False,
            "thumbnailUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=600&fit=crop"
        },
        {
            "id": "classic_1",
            "name": "Classic Estate",
            "description": "A traditional layout suitable for historical or classic homes.",
            "isPremium": False,
            "thumbnailUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=600&fit=crop"
        },
        {
            "id": "luxury_1",
            "name": "Luxury Series",
            "description": "Premium templating optimized for high-end real estate properties.",
            "isPremium": True,
            "thumbnailUrl": "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=400&h=600&fit=crop"
        }
    ]

def generate_brochure(input_data: BrochureInput) -> bytes:
    """
    Generate a property brochure PDF and return it as bytes.
    """
    html_content = f"""
    <html>
        <head>
            <style>
                body {{ font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #333; background-color: #fcfcfc; }}
                .card {{ background: white; border-radius: 12px; padding: 30px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }}
                h1 {{ color: #2c3e50; font-size: 32px; border-bottom: 2px solid #e0e0e0; padding-bottom: 10px; }}
                h2 {{ color: #e74c3c; font-weight: normal; }}
                p {{ font-size: 16px; line-height: 1.6; color: #555; }}
                .meta {{ background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 25px 0; border: 1px solid #e9ecef; display: table; width: 100%; }}
                .meta-item {{ display: table-cell; text-align: center; border-right: 1px solid #e9ecef; }}
                .meta-item:last-child {{ border-right: none; }}
                .meta-val {{ font-size: 24px; font-weight: bold; color: #2c3e50; }}
                .meta-lbl {{ font-size: 14px; color: #7f8c8d; text-transform: uppercase; letter-spacing: 1px; margin-top: 5px; }}
                .footer {{ margin-top: 60px; text-align: center; font-size: 12px; color: #aaa; border-top: 1px solid #eee; padding-top: 20px; }}
            </style>
        </head>
        <body>
            <div class="card">
                <h1>{input_data.title or 'Premium Property'}</h1>
                <h2>{input_data.address or 'Address not provided'}</h2>
                
                <div class="meta">
                    <div class="meta-item">
                        <div class="meta-val">${input_data.price or 'TBA'}</div>
                        <div class="meta-lbl">Price</div>
                    </div>
                    <div class="meta-item">
                        <div class="meta-val">{input_data.bedrooms or 0}</div>
                        <div class="meta-lbl">Beds</div>
                    </div>
                    <div class="meta-item">
                        <div class="meta-val">{input_data.bathrooms or 0}</div>
                        <div class="meta-lbl">Baths</div>
                    </div>
                    <div class="meta-item">
                        <div class="meta-val">{input_data.sqft or 0}</div>
                        <div class="meta-lbl">Sq. Ft.</div>
                    </div>
                </div>
                
                <h3>Description</h3>
                <p>{input_data.description or 'A beautiful property waiting for its new owner. Impeccably maintained interior and modern layout perfectly matching its environment.'}</p>
                
                <div class="footer">
                    Generated by AtlasVS Brochure Tool
                </div>
            </div>
        </body>
    </html>
    """
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes
    except Exception as e:
        print(f"Weasyprint error: {e}")
        # Return a simple minimal PDF if weasyprint fails
        return b"%PDF-1.4\n1 0 obj <</Type/Catalog/Pages 2 0 R>> endobj\n2 0 obj <</Type/Pages/Count 1/Kids[3 0 R]>> endobj\n3 0 obj <</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<<>>/Contents 4 0 R>> endobj\n4 0 obj <</Length 21>> stream\nBT /F1 24 Tf 100 700 Td (AtlasVS Brochure generation fallback. Weasyprint not available.) Tj ET\nendstream endobj\nxref\n0 5\n0000000000 65535 f\n0000000009 00000 n\n0000000052 00000 n\n0000000101 00000 n\n0000000186 00000 n\ntrailer <</Size 5/Root 1 0 R>>\nstartxref\n258\n%%EOF"
