from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from enum import Enum
import io

class LanguageCode(str, Enum):
    EN = "en"
    TR = "tr"
    ZH = "zh"
    KO = "ko"
    AR = "ar"
    RU = "ru"

class BrochureInput(BaseModel):
    property_id: Optional[str] = None
    template: str = "modern_1"
    language: LanguageCode = LanguageCode.EN
    custom_photos: Optional[List[str]] = None
    title: Optional[str] = None
    address: Optional[str] = None
    description: Optional[str] = None
    price: Optional[float] = None
    bedrooms: Optional[int] = None
    bathrooms: Optional[int] = None
    sqft: Optional[int] = None
    qr_code_url: Optional[str] = None
    agent_name: Optional[str] = "Reservatior Preferred Agent"
    agent_contact: Optional[str] = "+1 (800) RESERV"

# Multilingual Labels Catalogue
_TRANSLATIONS: Dict[LanguageCode, Dict[str, str]] = {
    LanguageCode.EN: {
        "price": "Price",
        "beds": "Beds",
        "baths": "Baths",
        "sqft": "Sq. Ft.",
        "description": "Property Overview",
        "features": "Key Highlights",
        "scan_tour": "Scan to view 3D Virtual Tour",
        "contact_agent": "Exclusively Marketed By",
        "footer": "Generated by Reservatior Universal Property OS",
    },
    LanguageCode.TR: {
        "price": "Fiyat",
        "beds": "Yatak O.",
        "baths": "Banyo",
        "sqft": "m²",
        "description": "Gayrimenkul Özet Bilgisi",
        "features": "Öne Çıkan Özellikler",
        "scan_tour": "3D Sanal Tur İçin QR Kodu Okutun",
        "contact_agent": "Yetkili Emlak Danışmanı",
        "footer": "Reservatior Gayrimenkul İşletim Sistemi Tarafından Üretilmiştir",
    },
    LanguageCode.ZH: {
        "price": "价格",
        "beds": "卧室",
        "baths": "浴室",
        "sqft": "平方英尺",
        "description": "房产概览",
        "features": "核心亮点",
        "scan_tour": "扫描二维码查看3D虚拟看房",
        "contact_agent": "独家代理经纪人",
        "footer": "由 Reservatior 通用房产操作系统生成",
    },
    LanguageCode.KO: {
        "price": "매매가",
        "beds": "침실",
        "baths": "욕실",
        "sqft": "평형/sqft",
        "description": "매물 개요",
        "features": "주요 특징",
        "scan_tour": "3D 가상 투어를 보려면 QR 코드를 스캔하세요",
        "contact_agent": "전담 에이전트",
        "footer": "Reservatior 프라퍼티 OS에 의해 생성됨",
    },
    LanguageCode.AR: {
        "price": "السعر",
        "beds": "غرف النوم",
        "baths": "الحمامات",
        "sqft": "المساحة",
        "description": "نظرة عامة على العقار",
        "features": "أبرز المميزات",
        "scan_tour": "امسح الرمز لمشاهدة الجولة الافتراضية ثلاثية الأبعاد",
        "contact_agent": "المسوق العقاري الحصري",
        "footer": "تم الإنشاء بواسطة نظام التشغيل العقاري العالمي Reservatior",
    },
    LanguageCode.RU: {
        "price": "Цена",
        "beds": "Spal'ni",
        "baths": "Vannye",
        "sqft": "Ploshchad'",
        "description": "Obzor nedvizhimosti",
        "features": "Klyuchevye osobennosti",
        "scan_tour": "Otskanyrujte dlya 3D-tura",
        "contact_agent": "Eksklyuzivnyj agenty",
        "footer": "Sformirovano Reservatior Property OS",
    },
}

def get_templates() -> list:
    return [
        {
            "id": "modern_1",
            "name": "Modern Elegance",
            "description": "A clean, modern style brochure focusing on large high-quality photos.",
            "isPremium": False,
            "thumbnailUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=600&fit=crop"
        },
        {
            "id": "classic_1",
            "name": "Classic Estate",
            "description": "A traditional layout suitable for historical or classic homes.",
            "isPremium": False,
            "thumbnailUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=600&fit=crop"
        },
        {
            "id": "luxury_1",
            "name": "Luxury Series",
            "description": "Premium templating optimized for high-end real estate properties.",
            "isPremium": True,
            "thumbnailUrl": "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=400&h=600&fit=crop"
        }
    ]

def generate_brochure(input_data: BrochureInput) -> bytes:
    """
    Generate a multilingual property brochure PDF and return it as bytes.
    """
    labels = _TRANSLATIONS.get(input_data.language, _TRANSLATIONS[LanguageCode.EN])
    is_rtl = input_data.language == LanguageCode.AR

    direction = "rtl" if is_rtl else "ltr"
    align_style = "right" if is_rtl else "left"

    html_content = f"""
    <!DOCTYPE html>
    <html dir="{direction}">
        <head>
            <meta charset="utf-8">
            <style>
                body {{ 
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                    padding: 40px; 
                    color: #1a202c; 
                    background-color: #f7fafc; 
                    direction: {direction};
                    text-align: {align_style};
                }}
                .card {{ 
                    background: white; 
                    border-radius: 16px; 
                    padding: 35px; 
                    box-shadow: 0 10px 25px rgba(0,0,0,0.08); 
                    border: 1px solid #e2e8f0;
                }}
                .header-line {{
                    height: 4px;
                    background: linear-gradient(90deg, #3182ce, #805ad5);
                    border-radius: 2px;
                    margin-bottom: 25px;
                }}
                h1 {{ color: #2d3748; font-size: 30px; margin-bottom: 5px; font-weight: 700; }}
                h2 {{ color: #718096; font-size: 16px; font-weight: 400; margin-top: 0; margin-bottom: 25px; }}
                p {{ font-size: 15px; line-height: 1.7; color: #4a5568; }}
                .meta {{ 
                    background: #edf2f7; 
                    padding: 20px; 
                    border-radius: 12px; 
                    margin: 25px 0; 
                    display: table; 
                    width: 100%; 
                    box-sizing: border-box;
                }}
                .meta-item {{ display: table-cell; text-align: center; border-right: 1px solid #cbd5e0; }}
                .meta-item:last-child {{ border-right: none; }}
                .meta-val {{ font-size: 22px; font-weight: bold; color: #2b6cb0; }}
                .meta-lbl {{ font-size: 12px; color: #718096; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }}
                .agent-box {{
                    margin-top: 30px;
                    background: #f7fafc;
                    border: 1px dashed #cbd5e0;
                    padding: 15px 20px;
                    border-radius: 8px;
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                }}
                .footer {{ margin-top: 50px; text-align: center; font-size: 11px; color: #a0aec0; border-top: 1px solid #e2e8f0; padding-top: 15px; }}
            </style>
        </head>
        <body>
            <div class="card">
                <div class="header-line"></div>
                <h1>{input_data.title or 'Exclusive Property Listing'}</h1>
                <h2>{input_data.address or 'Prime Location'}</h2>
                
                <div class="meta">
                    <div class="meta-item">
                        <div class="meta-val">${input_data.price:,.0f}</div>
                        <div class="meta-lbl">{labels['price']}</div>
                    </div>
                    <div class="meta-item">
                        <div class="meta-val">{input_data.bedrooms or '-'}</div>
                        <div class="meta-lbl">{labels['beds']}</div>
                    </div>
                    <div class="meta-item">
                        <div class="meta-val">{input_data.bathrooms or '-'}</div>
                        <div class="meta-lbl">{labels['baths']}</div>
                    </div>
                    <div class="meta-item">
                        <div class="meta-val">{input_data.sqft or '-'}</div>
                        <div class="meta-lbl">{labels['sqft']}</div>
                    </div>
                </div>
                
                <h3>{labels['description']}</h3>
                <p>{input_data.description or 'A beautiful property presented by Reservatior Property OS featuring dynamic staging, premium amenities, and investment-grade returns.'}</p>
                
                <div class="agent-box">
                    <div>
                        <strong style="color: #2d3748; font-size: 13px;">{labels['contact_agent']}</strong><br/>
                        <span style="font-size: 14px; color: #3182ce;">{input_data.agent_name}</span> | {input_data.agent_contact}
                    </div>
                </div>

                <div class="footer">
                    {labels['footer']}
                </div>
            </div>
        </body>
    </html>
    """
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes
    except Exception as e:
        print(f"Weasyprint warning: {e}")
        return b"%PDF-1.4\n1 0 obj <</Type/Catalog/Pages 2 0 R>> endobj\n2 0 obj <</Type/Pages/Count 1/Kids[3 0 R]>> endobj\n3 0 obj <</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Resources<<>>/Contents 4 0 R>> endobj\n4 0 obj <</Length 21>> stream\nBT /F1 24 Tf 100 700 Td (Reservatior Multilingual Brochure PDF Fallback.) Tj ET\nendstream endobj\nxref\n0 5\n0000000000 65535 f\n0000000009 00000 n\n0000000052 00000 n\n0000000101 00000 n\n0000000186 00000 n\ntrailer <</Size 5/Root 1 0 R>>\nstartxref\n258\n%%EOF"
