name: reservatior
description: AI-powered Real Estate Media SaaS — Global Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.3 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # Networking
  dio: ^5.7.0

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Media
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  video_player: ^2.9.1
  chewie: ^1.8.5

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.69.0
  dotted_border: ^2.1.0

  # Utilities
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  logger: ^2.4.0
  uuid: ^4.5.1

  # Social Auth
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  decimal: ^3.2.4
  timeago: ^3.7.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
