
//***  AUTO-GENERATED FILE - DO NOT MODIFY ***// 
enum CommissionTypeUS {
    BUYER_AGENT_COMMISSION,
	SELLER_AGENT_COMMISSION,
	REFERRAL_FEE,
	TRANSACTION_COORDINATOR_FEE,
	TITLE_COMPANY_FEE,
	ESCROW_FEE,
	APPRAISAL_FEE,
	HOME_INSPECTION_FEE,
	PROPERTY_MANAGEMENT_FEE,
	LEASING_COMMISSION,
	MAINTENANCE_FEE,
	MARKETING_FEE,
	ADMINISTRATIVE_FEE,
	PROCESSING_FEE;
   
    String toJson() => toString().split('.').last;

    factory CommissionTypeUS.fromJson(String name) => values.byName(name);
  
}
