
//***  AUTO-GENERATED FILE - DO NOT MODIFY ***// 
enum FacilityType {
    RESIDENTIAL,
	COMMERCIAL,
	MIXED_USE,
	INDUSTRIAL,
	OFFICE,
	RETAIL,
	WAREHOUSE,
	PARKING,
	GYM,
	SWIMMING_POOL,
	YOGA,
	FITNESS,
	GOLF,
	CAFETERIA,
	RESTAURANT,
	THEATER,
	CONCERT_HALL,
	MUSEUM,
	GALLERY,
	CINEMA,
	ZOO,
	BOTANIC_GARDEN,
	THEME_PARK,
	GOLF_COURSE,
	BEACH,
	PARK,
	RESIDENTIAL_COMPLEX,
	COMMERCIAL_COMPLEX,
	LUXURY_RESIDENCE,
	APARTMENT_BUILDING,
	TOWER_COMPLEX,
	GATED_COMMUNITY;
   
    String toJson() => toString().split('.').last;

    factory FacilityType.fromJson(String name) => values.byName(name);
  
}
