
//***  AUTO-GENERATED FILE - DO NOT MODIFY ***// 
enum InspectionTypeUS {
    HOME_INSPECTION,
	RADON_TESTING,
	MOLD_INSPECTION,
	PEST_INSPECTION,
	LEAD_PAINT_INSPECTION,
	ELECTRICAL_INSPECTION,
	PLUMBING_INSPECTION,
	HVAC_INSPECTION,
	ROOF_INSPECTION,
	FOUNDATION_INSPECTION,
	FIRE_SAFETY_INSPECTION,
	CODE_COMPLIANCE_INSPECTION;
   
    String toJson() => toString().split('.').last;

    factory InspectionTypeUS.fromJson(String name) => values.byName(name);
  
}
