
//***  AUTO-GENERATED FILE - DO NOT MODIFY ***// 
enum NotificationType {
    MENTION,
	TASK_ASSIGNED,
	BOOKING_CONFIRMED,
	REVIEW_RECEIVED,
	PRICE_CHANGE,
	SYSTEM_UPDATE,
	COMPLIANCE_ALERT,
	COMMUNICATION_RECEIVED,
	RENT_DUE,
	RENT_PAID,
	LEASE_EXPIRING,
	MAINTENANCE_REQUEST,
	LEASE_RENEWAL,
	LATE_PAYMENT_WARNING,
	LEASE_TERMINATION,
	RENT_INCREASE,
	COMMUNITY_NOTICE,
	POLICY_UPDATE,
	LIKE,
	COMMENT,
	FOLLOW,
	AVAILABILITY,
	OTHER;
   
    String toJson() => toString().split('.').last;

    factory NotificationType.fromJson(String name) => values.byName(name);
  
}
