
//***  AUTO-GENERATED FILE - DO NOT MODIFY ***// 
enum SharedAmenityType {
    SWIMMING_POOL,
	INDOOR_POOL,
	OUTDOOR_POOL,
	KIDS_POOL,
	FITNESS_CENTER,
	GYM,
	SPA,
	SAUNA,
	TENNIS_COURT,
	BASKETBALL_COURT,
	FOOTBALL_FIELD,
	CHILDREN_PLAYGROUND,
	PARK,
	GARDEN,
	TERRACE,
	ROOFTOP,
	CONCIERGE,
	SECURITY,
	PARKING,
	ELEVATOR,
	LIBRARY,
	MEETING_ROOM,
	EVENT_HALL,
	CAFE,
	RESTAURANT,
	MARKET,
	PHARMACY,
	MEDICAL_CENTER,
	SHUTTLE_SERVICE,
	CLEANING_SERVICE,
	MAINTENANCE_SERVICE;
   
    String toJson() => toString().split('.').last;

    factory SharedAmenityType.fromJson(String name) => values.byName(name);
  
}
