from enum import Enum

class SignatureStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_SIGNATURE = "PENDING_SIGNATURE"
    PARTIALLY_SIGNED = "PARTIALLY_SIGNED"
    SIGNED = "SIGNED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"

class SignerRole(str, Enum):
    TENANT = "TENANT"
    PROPERTY_OWNER = "PROPERTY_OWNER"
    AGENT = "AGENT"
    PROPERTY_MANAGER = "PROPERTY_MANAGER"
    SERVICE_PROVIDER = "SERVICE_PROVIDER"
    INVESTOR = "INVESTOR"
