// ignore_for_file: constant_identifier_names
enum AnalyticsType {
  LISTING_VIEW,
  BOOKING_CONVERSION,
  ML_PROPERTY_SCORE,
  USER_ENGAGEMENT,
  REVENUE,
  PERFORMANCE,
  AGENT_PERFORMANCE,
  AGENCY_PERFORMANCE,
  PROPERTY_VIEW,
  RESERVATION_CREATED,
  PAYMENT_RECEIVED,
  TAX_PAYMENT,
  TAX_OVERDUE,
  TAX_COMPLIANCE,
  TAX_REVENUE,
  TAX_PERFORMANCE,
  TAX_REMINDER,
  TAX_AUDIT,
  TAX_REPORT
}
