// ignore_for_file: constant_identifier_names
enum ComplianceType {
  FAIR_HOUSING_ACT,
  ADA_COMPLIANCE,
  ENERGY_EFFICIENCY,
  BUILDING_CODE,
  ELECTRICAL_SAFETY,
  FIRE_SAFETY,
  IMMIGRATION_CHECK,
  LEAD_PAINT_DISCLOSURE,
  MOLD_DISCLOSURE,
  FLOOD_INSURANCE,
  PROPERTY_TAXES,
  HOA_RULES
}
