// ignore_for_file: constant_identifier_names
enum DocumentTypeUSA {
  PURCHASE_AGREEMENT,
  LISTING_AGREEMENT,
  LEASE_AGREEMENT,
  DISCLOSURE_FORM,
  INSPECTION_REPORT,
  APPRAISAL_REPORT,
  TITLE_REPORT,
  CLOSING_STATEMENT,
  TAX_DOCUMENT,
  INSURANCE_POLICY,
  HOA_DOCUMENTS,
  PERMIT,
  LICENSE,
  CERTIFICATE,
  FINANCIAL_STATEMENT,
  VOIDED_CHECK,
  W9_FORM,
  FORM_1099
}
