// ignore_for_file: constant_identifier_names
enum EscrowTriggerEvent {
  RESERVATION_CONFIRMED,
  CHECK_IN_COMPLETED,
  MIDSTAY_REACHED,
  CHECK_OUT_COMPLETED,
  SURVEY_COMPLETED,
  DEPOSIT_INSPECTION_DONE,
  DISPUTE_RESOLVED,
  MANUAL_RELEASE
}
