// ignore_for_file: constant_identifier_names
enum LeaseTypeUS {
  MONTH_TO_MONTH_TENANCY,
  FIXED_TERM_LEASE,
  COMMERCIAL_LEASE,
  RESIDENTIAL_LEASE,
  SUBLEASE,
  ROOM_RENTAL_AGREEMENT,
  STUDENT_HOUSING_LEASE,
  VACATION_RENTAL_AGREEMENT,
  MOBILE_HOME_LEASE,
  STORAGE_UNIT_LEASE,
  OFFICE_LEASE,
  RETAIL_LEASE
}
