// ignore_for_file: constant_identifier_names
enum LedgerEventType {
  INCOME,
  EXPENSE,
  BILL,
  BOOKING_CREATED,
  BOOKING_UPDATED,
  LEASE_STARTED,
  LEASE_ENDED,
  CONTRACT_CREATED,
  CONTRACT_VERSIONED,
  CONTRACT_RENEWED,
  STATUS_CHANGED,
  MAINTENANCE_BLOCKED,
  OWNERSHIP_CHANGED,
  NOTE
}
