// ignore_for_file: constant_identifier_names
enum LocationAmenities {
  CITY_CENTER,
  BEACH,
  PARK,
  SHOPPING_MALL,
  HOSPITAL,
  SCHOOL,
  UNIVERSITY,
  POLICE_STATION,
  FIRE_STATION,
  PUBLIC_TRANSPORT,
  SUBWAY_STATION,
  BUS_STOP,
  AIRPORT,
  RESTAURANT_DISTRICT,
  ENTERTAINMENT_ZONE,
  BUSINESS_DISTRICT,
  CULTURAL_CENTER,
  MUSEUM,
  LIBRARY,
  SPORTS_COMPLEX
}
