// ignore_for_file: constant_identifier_names
enum ProjectAnalysisType {
  ARCHITECT,
  DATA_SCIENTIST,
  BUSINESS_ANALYST,
  SECURITY_EXPERT,
  PERFORMANCE_EXPERT,
  QA_SPECIALIST,
  UX_DESIGNER,
  MOBILE_DEVELOPER,
  DEVOPS_ENGINEER
}
