// ignore_for_file: constant_identifier_names
enum PropertyType {
  DETACHED_HOUSE,
  SEMI_DETACHED_HOUSE,
  TERRACED_HOUSE,
  FLAT_MAISONETTE,
  BUNGALOW,
  COTTAGE,
  TOWNHOUSE,
  APARTMENT,
  STUDIO,
  PENTHOUSE,
  OFFICE,
  RETAIL,
  COMMERCIAL_SPACE,
  SINGLE_FAMILY,
  CONDO_APARTMENT,
  MULTI_FAMILY,
  COMPOUND,
  VILLA,
  ADU_GUEST_HOUSE,
  CABIN_TINY_HOUSE,
  COMMERCIAL
}
