// ignore_for_file: constant_identifier_names
enum PropertyFeatures {
  FURNISHED,
  PARTIALLY_FURNISHED,
  UNFURNISHED,
  OPEN_FLOOR_PLAN,
  HIGH_CEILING,
  BALCONY,
  TERRACE,
  GARDEN,
  SEA_VIEW,
  MOUNTAIN_VIEW,
  CITY_VIEW,
  SMART_HOME,
  ENERGY_EFFICIENT,
  SOLAR_PANELS,
  EARTHQUAKE_RESISTANT,
  SOUNDPROOF,
  WHEELCHAIR_ACCESSIBLE,
  PET_FRIENDLY,
  HOME_OFFICE,
  WALK_IN_CLOSET
}
