// ignore_for_file: constant_identifier_names
enum ReportType {
  FINANCIAL,
  PERFORMANCE,
  COMPLIANCE,
  MARKET_ANALYSIS,
  REVENUE,
  OCCUPANCY,
  GUEST_ANALYSIS,
  OFFER_PERFORMANCE,
  RESERVATION_SUMMARY,
  EXPENSE_TRACKING,
  TASK_MANAGEMENT,
  PROPERTY_PERFORMANCE
}
