import { TaxRateInfo } from "./globaltaxregulation";

export const USA_TAX_RATES: TaxRateInfo[] = [
  { country: "USA", countryCode: "US-AL", taxAuthority: "Alabama Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.04 },
  { country: "USA", countryCode: "US-AK", taxAuthority: "N/A", taxType: "Sales Tax", standardRate: 0.00 },
  { country: "USA", countryCode: "US-AZ", taxAuthority: "Arizona Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.056 },
  { country: "USA", countryCode: "US-AR", taxAuthority: "Arkansas Dept. of Finance", taxType: "Sales Tax", standardRate: 0.065 },
  { country: "USA", countryCode: "US-CA", taxAuthority: "CDTFA", taxType: "Sales Tax", standardRate: 0.0725 },
  { country: "USA", countryCode: "US-CO", taxAuthority: "Colorado Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.029 },
  { country: "USA", countryCode: "US-CT", taxAuthority: "CT Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.0635 },
  { country: "USA", countryCode: "US-DE", taxAuthority: "N/A", taxType: "Sales Tax", standardRate: 0.00 },
  { country: "USA", countryCode: "US-DC", taxAuthority: "Office of Tax and Revenue", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-FL", taxAuthority: "Florida Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-GA", taxAuthority: "Georgia Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.04 },
  { country: "USA", countryCode: "US-HI", taxAuthority: "Hawaii Dept. of Taxation", taxType: "GET", standardRate: 0.04 },
  { country: "USA", countryCode: "US-ID", taxAuthority: "Idaho State Tax Commission", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-IL", taxAuthority: "Illinois Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.0625 },
  { country: "USA", countryCode: "US-IN", taxAuthority: "Indiana Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.07 },
  { country: "USA", countryCode: "US-IA", taxAuthority: "Iowa Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-KS", taxAuthority: "Kansas Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.065 },
  { country: "USA", countryCode: "US-KY", taxAuthority: "Kentucky Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-LA", taxAuthority: "Louisiana Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.0445 },
  { country: "USA", countryCode: "US-ME", taxAuthority: "Maine Revenue Services", taxType: "Sales Tax", standardRate: 0.055 },
  { country: "USA", countryCode: "US-MD", taxAuthority: "Comptroller of Maryland", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-MA", taxAuthority: "Massachusetts Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.0625 },
  { country: "USA", countryCode: "US-MI", taxAuthority: "Michigan Dept. of Treasury", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-MN", taxAuthority: "Minnesota Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.06875 },
  { country: "USA", countryCode: "US-MS", taxAuthority: "Mississippi Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.07 },
  { country: "USA", countryCode: "US-MO", taxAuthority: "Missouri Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.04225 },
  { country: "USA", countryCode: "US-MT", taxAuthority: "N/A", taxType: "Sales Tax", standardRate: 0.00 },
  { country: "USA", countryCode: "US-NE", taxAuthority: "Nebraska Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.055 },
  { country: "USA", countryCode: "US-NV", taxAuthority: "Nevada Dept. of Taxation", taxType: "Sales Tax", standardRate: 0.0685 },
  { country: "USA", countryCode: "US-NH", taxAuthority: "N/A", taxType: "Sales Tax", standardRate: 0.00 },
  { country: "USA", countryCode: "US-NJ", taxAuthority: "New Jersey Div. of Taxation", taxType: "Sales Tax", standardRate: 0.06625 },
  { country: "USA", countryCode: "US-NM", taxAuthority: "NM Taxation & Revenue", taxType: "Gross Receipts Tax", standardRate: 0.05125 },
  { country: "USA", countryCode: "US-NY", taxAuthority: "NY Dept. of Taxation", taxType: "Sales Tax", standardRate: 0.04 },
  { country: "USA", countryCode: "US-NC", taxAuthority: "NC Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.0475 },
  { country: "USA", countryCode: "US-ND", taxAuthority: "ND State Tax Commissioner", taxType: "Sales Tax", standardRate: 0.05 },
  { country: "USA", countryCode: "US-OH", taxAuthority: "Ohio Dept. of Taxation", taxType: "Sales Tax", standardRate: 0.0575 },
  { country: "USA", countryCode: "US-OK", taxAuthority: "Oklahoma Tax Commission", taxType: "Sales Tax", standardRate: 0.045 },
  { country: "USA", countryCode: "US-OR", taxAuthority: "N/A", taxType: "Sales Tax", standardRate: 0.00 },
  { country: "USA", countryCode: "US-PA", taxAuthority: "Pennsylvania Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-RI", taxAuthority: "Rhode Island Div. of Taxation", taxType: "Sales Tax", standardRate: 0.07 },
  { country: "USA", countryCode: "US-SC", taxAuthority: "SC Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-SD", taxAuthority: "SD Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.045 },
  { country: "USA", countryCode: "US-TN", taxAuthority: "Tennessee Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.07 },
  { country: "USA", countryCode: "US-TX", taxAuthority: "Texas Comptroller", taxType: "Sales Tax", standardRate: 0.0625 },
  { country: "USA", countryCode: "US-UT", taxAuthority: "Utah State Tax Commission", taxType: "Sales Tax", standardRate: 0.061 },
  { country: "USA", countryCode: "US-VT", taxAuthority: "Vermont Dept. of Taxes", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-VA", taxAuthority: "Virginia Dept. of Taxation", taxType: "Sales Tax", standardRate: 0.053 },
  { country: "USA", countryCode: "US-WA", taxAuthority: "Washington Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.065 },
  { country: "USA", countryCode: "US-WV", taxAuthority: "WV State Tax Dept.", taxType: "Sales Tax", standardRate: 0.06 },
  { country: "USA", countryCode: "US-WI", taxAuthority: "Wisconsin Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.05 },
  { country: "USA", countryCode: "US-WY", taxAuthority: "Wyoming Dept. of Revenue", taxType: "Sales Tax", standardRate: 0.04 }
];

export const EUROPE_TAX_RATES: TaxRateInfo[] = [
  { countryCode: "AT", country: "Austria", taxAuthority: "BMF", taxType: "VAT", standardRate: 0.20 },
  { countryCode: "BE", country: "Belgium", taxAuthority: "FPS Finance", taxType: "VAT", standardRate: 0.21 },
  { countryCode: "BG", country: "Bulgaria", taxAuthority: "NRA", taxType: "VAT", standardRate: 0.20 },
  { countryCode: "HR", country: "Croatia", taxAuthority: "Tax Admin", taxType: "VAT", standardRate: 0.25 },
  { countryCode: "CY", country: "Cyprus", taxAuthority: "Tax Dept", taxType: "VAT", standardRate: 0.19 },
  { countryCode: "CZ", country: "Czechia", taxAuthority: "Financial Admin", taxType: "VAT", standardRate: 0.21 },
  { countryCode: "DK", country: "Denmark", taxAuthority: "Skat", taxType: "VAT", standardRate: 0.25 },
  { countryCode: "EE", country: "Estonia", taxAuthority: "Tax & Customs", taxType: "VAT", standardRate: 0.22 },
  { countryCode: "FI", country: "Finland", taxAuthority: "Vero", taxType: "VAT", standardRate: 0.24 },
  { countryCode: "FR", country: "France", taxAuthority: "DGFiP", taxType: "VAT", standardRate: 0.20 },
  { countryCode: "DE", country: "Germany", taxAuthority: "Finanzamt", taxType: "VAT", standardRate: 0.19 },
  { countryCode: "GR", country: "Greece", taxAuthority: "IAPR", taxType: "VAT", standardRate: 0.24 },
  { countryCode: "HU", country: "Hungary", taxAuthority: "NAV", taxType: "VAT", standardRate: 0.27 },
  { countryCode: "IE", country: "Ireland", taxAuthority: "Revenue", taxType: "VAT", standardRate: 0.23 },
  { countryCode: "IT", country: "Italy", taxAuthority: "Agenzia Entrate", taxType: "VAT", standardRate: 0.22 },
  { countryCode: "LV", country: "Latvia", taxAuthority: "VID", taxType: "VAT", standardRate: 0.21 },
  { countryCode: "LT", country: "Lithuania", taxAuthority: "VMI", taxType: "VAT", standardRate: 0.21 },
  { countryCode: "LU", country: "Luxembourg", taxAuthority: "AED", taxType: "VAT", standardRate: 0.17 },
  { countryCode: "MT", country: "Malta", taxAuthority: "Revenue Comm", taxType: "VAT", standardRate: 0.18 },
  { countryCode: "NL", country: "Netherlands", taxAuthority: "Belastingdienst", taxType: "VAT", standardRate: 0.21 },
  { countryCode: "PL", country: "Poland", taxAuthority: "KAS", taxType: "VAT", standardRate: 0.23 },
  { countryCode: "PT", country: "Portugal", taxAuthority: "AT", taxType: "VAT", standardRate: 0.23 },
  { countryCode: "RO", country: "Romania", taxAuthority: "ANAF", taxType: "VAT", standardRate: 0.19 },
  { countryCode: "SK", country: "Slovakia", taxAuthority: "Fin. Directorate", taxType: "VAT", standardRate: 0.20 },
  { countryCode: "SI", country: "Slovenia", taxAuthority: "FURS", taxType: "VAT", standardRate: 0.22 },
  { countryCode: "ES", country: "Spain", taxAuthority: "AEAT", taxType: "VAT", standardRate: 0.21 },
  { countryCode: "SE", country: "Sweden", taxAuthority: "Skatteverket", taxType: "VAT", standardRate: 0.25 },
  { countryCode: "CH", country: "Switzerland", taxAuthority: "FTA", taxType: "VAT", standardRate: 0.081 },
  { countryCode: "NO", country: "Norway", taxAuthority: "Skatteetaten", taxType: "VAT", standardRate: 0.25 },
  { countryCode: "GB", country: "United Kingdom", taxAuthority: "HMRC", taxType: "VAT", standardRate: 0.20 }
];
