// Prisma Generator için Valibot Integration
// Bu yaklaşım henüz resmi olmayan alternatif bir yöntemdir

import { GeneratorOptions } from '@prisma/generator-helper';
import { parseEnvValue } from '@prisma/internals';

// Generator configuration
export interface ValibotGeneratorConfig {
  output: string;
  importPath?: string;
  generateTypes?: boolean;
  generateFilters?: boolean;
  generateQueries?: boolean;
}

// Main generator function
export async function generateValibot(options: GeneratorOptions) {
  const config = parseConfig(options.generator);
  const models = options.dmmf.mappings.modelOperations;
  
  console.log('🚀 Generating Valibot schemas from Prisma models...');
  
  let content = `// Generated by Prisma Valibot Generator
// Generated at: ${new Date().toISOString()}
// Prisma Schema: ${options.schemaPath}

import * as v from 'valibot';
${config.importPath ? `import type { ${models.map(m => m.model).join(', ')} } from '${config.importPath}';` : ''}

`;

  // Generate schemas for each model
  for (const model of models) {
    const modelData = options.dmmf.datamodel.models.find(m => m.name === model.model);
    if (modelData) {
      content += generateModelSchemas(modelData, config);
    }
  }
  
  // Write to output file
  await writeFile(config.output, content);
  console.log(`✅ Generated Valibot schemas: ${config.output}`);
}

function generateModelSchemas(model: any, config: ValibotGeneratorConfig): string {
  const modelName = model.name;
  const modelNameLower = modelName.charAt(0).toLowerCase() + modelName.slice(1);
  
  // Generate field mappings
  const fields = model.fields.map((field: any) => mapFieldToValibot(field));
  
  let content = `// ${modelName} Schemas
`;

  if (config.generateTypes !== false) {
    // Create schema
    const requiredFields = fields.filter((f: any) => !f.isOptional && !f.hasDefaultValue && !f.isId && !f.isTimestamp);
    content += `export const ${modelNameLower}CreateSchema = v.object({
${requiredFields.map((f: any) => `  ${f.name}: ${f.definition},`).join('\n')}
});

`;
    
    // Update schema
    const updatableFields = fields.filter((f: any) => !f.isId && !f.isTimestamp);
    content += `export const ${modelNameLower}UpdateSchema = v.partial(v.object({
${updatableFields.map((f: any) => `  ${f.name}: v.optional(${f.definition}),`).join('\n')}
}));

`;
  }
  
  if (config.generateFilters !== false) {
    // Filter schema
    content += `export const ${modelNameLower}FilterSchema = v.object({
${fields.map((f: any) => `  ${f.name}: v.optional(${f.definition}),`).join('\n')}
});

`;
  }
  
  if (config.generateQueries !== false) {
    // Query schema with pagination
    content += `export const ${modelNameLower}QuerySchema = v.object({
  page: v.optional(v.pipe(v.string(), v.transform(Number), v.minValue(1))),
  limit: v.optional(v.pipe(v.string(), v.transform(Number), v.minValue(1), v.maxValue(100))),
  sortBy: v.optional(v.string()),
  sortOrder: v.optional(v.union([v.literal('asc'), v.literal('desc')])),
  ...${modelNameLower}FilterSchema.entries
});

`;
  }
  
  // Type exports
  content += `export type ${modelName}Create = v.InferOutput<typeof ${modelNameLower}CreateSchema>;
export type ${modelName}Update = v.InferOutput<typeof ${modelNameLower}UpdateSchema>;
export type ${modelName}Filter = v.InferOutput<typeof ${modelNameLower}FilterSchema>;
export type ${modelName}Query = v.InferOutput<typeof ${modelNameLower}QuerySchema>;

`;
  
  return content;
}

function mapFieldToValibot(field: any): any {
  const { name, type, kind, isOptional, hasDefaultValue, isList, documentation } = field;
  
  // Determine if field is ID or timestamp
  const isId = name === 'id' || name.endsWith('Id');
  const isTimestamp = ['createdAt', 'updatedAt', 'deletedAt'].includes(name);
  
  // Base definition
  let definition = mapTypeToValibot(type, kind, name);
  
  // Add validations based on field name and documentation
  if (documentation) {
    const validations = parseValidationsFromDocs(documentation);
    definition = applyValidations(definition, validations);
  }
  
  // Add common validations
  if (name.includes('email')) {
    definition = 'v.pipe(v.string(), v.email())';
  }
  if (name.includes('password')) {
    definition = 'v.pipe(v.string(), v.minLength(8))';
  }
  if (name.includes('url')) {
    definition = 'v.pipe(v.string(), v.url())';
  }
  if (isId && type === 'String') {
    definition = 'v.pipe(v.string(), v.cuid())';
  }
  
  return {
    name,
    definition,
    isOptional: isOptional || hasDefaultValue,
    isId,
    isTimestamp,
    isList
  };
}

function mapTypeToValibot(type: string, kind: string, fieldName: string): string {
  switch (type) {
    case 'String':
      return 'v.string()';
    case 'Int':
      return 'v.pipe(v.number(), v.integer())';
    case 'Float':
    case 'Decimal':
      return 'v.number()';
    case 'Boolean':
      return 'v.boolean()';
    case 'DateTime':
      return 'v.string()'; // DateTime usually comes as string from API
    case 'Json':
      return 'v.record(v.string(), v.unknown())';
    case 'BigInt':
      return 'v.bigint()';
    case 'Bytes':
      return 'v.instanceof(Uint8Array)';
    default:
      if (kind === 'enum') {
        return 'v.string()'; // Enums would need special handling
      }
      return 'v.unknown()';
  }
}

function parseValidationsFromDocs(docs: string): any[] {
  // Parse validations from Prisma field documentation
  // Example: /// @minLength(5) @email
  const validations = [];
  const regex = /@(\w+)(?:\(([^)]+)\))?/g;
  let match;
  
  while ((match = regex.exec(docs)) !== null) {
    const [, validation, value] = match;
    validations.push({ type: validation, value });
  }
  
  return validations;
}

function applyValidations(baseDefinition: string, validations: any[]): string {
  let definition = baseDefinition;
  
  for (const validation of validations) {
    switch (validation.type) {
      case 'minLength':
        definition = `v.pipe(${definition}, v.minLength(${validation.value}))`;
        break;
      case 'maxLength':
        definition = `v.pipe(${definition}, v.maxLength(${validation.value}))`;
        break;
      case 'min':
        definition = `v.pipe(${definition}, v.minValue(${validation.value}))`;
        break;
      case 'max':
        definition = `v.pipe(${definition}, v.maxValue(${validation.value}))`;
        break;
      // Add more validation types as needed
    }
  }
  
  return definition;
}

function parseConfig(generator: any): ValibotGeneratorConfig {
  return {
    output: parseEnvValue(generator.output),
    importPath: generator.config.importPath,
    generateTypes: generator.config.generateTypes !== false,
    generateFilters: generator.config.generateFilters !== false,
    generateQueries: generator.config.generateQueries !== false,
  };
}

async function writeFile(path: string, content: string) {
  const fs = await import('fs/promises');
  await fs.writeFile(path, content, 'utf-8');
}
